apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  type: LoadBalancer
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: tcp-app
