apiVersion: v1
kind: Service
metadata:
  name: nginx-np-svc
  labels:
    app: nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
