apiVersion: v1
kind: Service
metadata:
  name: nginx-ci-svc
  labels:
    app: nginx-deployment
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-deployment
status:
  loadBalancer: {}
