apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
  labels:
    app: nginx-deployment
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
